// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type GoogleAuth struct {
	UserID       string
	CreatedAt    int64
	UpdatedAt    int64
	TokenExpiry  int64
	AccessToken  string
	RefreshToken string
}

type StagedInvoice struct {
	ID             string
	UserID         string
	GmailMessageID string
	GmailThreadID  string
	Status         string
	Sender         string
	Subject        string
	Snippet        sql.NullString
	HasAttachment  bool
	ReceivedAt     int64
	CreatedAt      int64
	UpdatedAt      int64
}

type User struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
	Email     string
}
