// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type GoogleAuth struct {
	UserID       string
	CreatedAt    int64
	UpdatedAt    int64
	TokenExpiry  int64
	AccessToken  string
	RefreshToken string
}

type User struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
	Email     string
}
